# Generated by Django 3.2.15 on 2022-09-15 12:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('CompanyID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=100)),
                ('CompanyCEO', models.CharField(max_length=55)),
                ('CompanyAddress', models.CharField(max_length=250)),
                ('InceptionDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('TeamID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('TeamLead', models.CharField(max_length=55)),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_details', to='tech.company')),
            ],
        ),
    ]
