# Generated by Django 3.2.15 on 2022-09-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-InceptionDate']},
        ),
    ]
