# Generated by Django 3.2.15 on 2022-09-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='InceptionDate',
            field=models.DateTimeField(),
        ),
    ]
