# Generated by Django 3.2.15 on 2022-09-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0006_alter_company_inceptiondate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
    ]
