# Generated by Django 3.2.15 on 2022-09-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0007_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-InceptionDate']},
        ),
        migrations.AlterField(
            model_name='company',
            name='InceptionDate',
            field=models.DateField(),
        ),
    ]
