# Generated by Django 3.2.7 on 2022-09-16 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0017_alter_company_inceptiondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='InceptionDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 23, 34, 53, 778316)),
        ),
    ]
